Updated PGSQL | CloudInit | EPEL | Services

diff --git a/services/updateSSHSudoersService b/services/updateSSHSudoersService
--- a/services/updateSSHSudoersService
+++ b/services/updateSSHSudoersService
@@ -48,7 +48,11 @@ case "$1" in
         echo -e "\nFunction : Start : Starting updateSSHSudoers from Cloud-Init...\n"
         # every time about starting up instance
         /usr/local/sbin/custom-scripts/python/updateSSHSudoers.py
-        echo -e "\nFunction : SSHD  : Reloaded\n"
+        if [[ $? -eq 0 ]]; then
+                echo -e "\nFunction : SSHD  : Started\n"
+        else
+                echo -e "Service failed"
+        fi
         /bin/systemctl reload sshd
         ;;
 
