Created Ansible: EPEL Repo

diff --git a/services/updateSSHSudoersService b/services/updateSSHSudoersService
--- a/services/updateSSHSudoersService
+++ b/services/updateSSHSudoersService
@@ -45,10 +45,14 @@
 case "$1" in
     start)
         # Printing the message
-        echo -e "\nFunction : Start : Starting updateSSHSudoers from Cloud-Init...\n"
+        echo -e "Starting service updateSSHSudoers from Cloud-Init..."
         # every time about starting up instance
         /usr/local/sbin/custom-scripts/python/updateSSHSudoers.py
-        echo -e "\nFunction : SSHD  : Reloaded\n"
+        if [[ $? -eq 0 ]]; then
+                echo -e "Successfully Started"
+        else
+                echo -e "Service Failed to Start"
+        fi
         /bin/systemctl reload sshd
         ;;
 
